name = "Pandaqi"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://pandaqi.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = ""
  homepage = ""
