baseURL         = "https://pandaqi.com"
theme           = "pandaqi"
title       	= "Pandaqi Games | Development Environment"
languageCode    = "en-US"
SectionPagesMenu = "main"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false

[permalinks]
  post = "/:slug/"

# SOURCE: https://discourse.gohugo.io/t/jsconfig-json-clarification/46386
# SOURCE: https://code.visualstudio.com/docs/languages/jsconfig
[build]
  noJSConfigInAssets = true

[params]
  heroImage = true
  title = "Pandaqi"
  subtitle = "Board & Video Game Developer"

  description = "The official website of game studio Pandaqi"
  metaDescription = "The official website of game studio Pandaqi"
  
  pageNotFoundTitle = "404 - Page not found"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  platform = 'platform'
  genre = 'genre'
  language = 'language'
  playtime = 'playtime'
  playercount = 'playercount'
  multiplayertype = 'multiplayertype'
  multiplayermode = 'multiplayermode'
  input = 'input'
  complexity = 'complexity'
  ages = 'ages'
  price = 'price'