baseURL         = "https://pandaqi.com"
theme           = "pandaqi"
title       	= "Pandaqi Games | Development Environment"
languageCode    = "en-US"
SectionPagesMenu = "main"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false

[permalinks]
  post = "/:slug/"

# SOURCE: https://discourse.gohugo.io/t/jsconfig-json-clarification/46386
# SOURCE: https://code.visualstudio.com/docs/languages/jsconfig
[build]
  noJSConfigInAssets = false

[params]
  title       = "Pandaqi"
  subtitle    = "Indie Game Developer"

  description = "The official website of game studio Pandaqi"
  metaDescription = "The official website of game studio Pandaqi"
  
  pageNotFoundTitle = "404 - Page not found"

  num_masks   = 8
  all_colors  = ["red", "blue", "green", "yellow", "orange", "turqoise", "beige", "purple", "pink", "darkblue", "brown", "white", "black"]
  slogans     = ["No, the game will not have online multiplayer", "Creating local multiplayer games until someone tells me to stop", "Creator of friendships, destroyer of friendships", "Couch co-op for everyone (who has a couch)", "Helping gamers and non-gamers connect", "Different games for a different experience"]
