enum Category
{
    POSITIVE = "positive",
    NEUTRAL = "neutral",
    NEGATIVE = "negative"
}

enum TokenType
{
    YES = "yes",
    NO = "no",
    SUPERYES = "superyes",
    SUPERNO = "superno"
}

interface TokenMetaData
{
    frame: number,
    colorBG: string
}

const TOKEN_TYPES:Record<TokenType, TokenMetaData> =
{
    [TokenType.YES]: { frame: 0, colorBG: "@TODO" },
    [TokenType.NO]: { frame: 1, colorBG: "@TODO" },
    [TokenType.SUPERYES]: { frame: 2, colorBG: "@TODO" },
    [TokenType.SUPERNO]: { frame: 3, colorBG: "@TODO" },
}

interface CategoryMetaData
{
    frame: number,
    colorBG: string,
    colorText: string
}

const CATEGORIES:Record<Category, CategoryMetaData> = 
{
    [Category.POSITIVE]: { frame: 0, colorBG: "@TODO", colorText: "@TODO" },
    [Category.NEUTRAL]: { frame: 1, colorBG: "@TODO", colorText: "@TODO" },
    [Category.NEGATIVE]: { frame: 2, colorBG: "@TODO", colorText: "@TODO" },
}

enum Pack
{
    BASE = "base",
    ADVANCED = "advanced",
    EXPERT = "expert",
    EXTRAORDINARY = "extraordinary"
}

type CategoryData = string;
type CategoryDataList = Record<Pack, CategoryData[]>;


const POSITIVE_CARDS:CategoryDataList = 
{
    [Pack.BASE]: [
        "You stay true to your personal values (whatever happens)",
        "You always look better when comparing yourself to others",
        "You immediately see through any lie",
        "You speak all languages in the world",
        "You get minimum wage for free every day",
        "You get the love of your live",
        "You can make anybody your friend by saying a magic word",
        "The tiniest events make you happy",
        "You can run faster than anyone in the world",
        "You can teleport",
        "You can read everyone's thoughts",
        "You can time travel",
        "You can turn yourself invisible",
        "You're the strongest person in the world",
        "You can fly",
        "You can heal any wound or illness",
        "You can shapeshift",
        "You have telekinesis ( = moving objects with your mind)",
        "You control the weather",
        "You are hyperintelligent",
        "You can communicate with animals",
        "You can create fire at will",
        "You can alter memories",
        "You can enter another's body",
        "You can see into the future",
        "You become a world-famous musician",
        "You become a loved celebrity",
        "You become filthy rich",
        "You can't make mistakes",
        "You can do actual magic",
        "You never have to sleep",
        "You have the most beautiful singing voice in the world",
        "Anything you dream becomes reality",
        "You can never be attacked or injured",
        "You truly believe everything's funny",
        "You can imitate the voice or mannerisms of anyone",
        "Your touch accelerates the growth of plants",
        "You can hug someone from a distance",
        "You can communicate with inanimate objects",
        "You can pause time by doing push-ups",
        "You have access to all paid content in the world",
        "You can change clothes at the snap of your fingers",
        "Dragons exist",
        "You are the sole leader of your country",
        "All your children are born perfectly healthy",
    ],

    [Pack.ADVANCED]: [
        "You can write an amazing novel or script in a week",
        "You can paint masterpieces with your eyes closed",
        "You invent a cure for all cancers",
        "You can earn lots of money just by exercising for an hour",
        "You can learn anything instantly",
        "You can control and manipulate dreams",
        "You remember everything you've ever read",
        "You get any job for which you apply",
        "You get any single degree you want",
        "Your days somehow contain 48 hours",
        "You can force others to speak the truth by touching their head",
        "You are exceptionally lucky",
        "You can control or reverse gravity",
        "You can create or remove light at will",
        "You stay young and healthy until you die at the life expectancy of that moment",
        "You are immortal",
        "Everything always smells nice to you",
        "You have the ability to grant wishes",
        "You have enhanced senses",
        "You are telepathic",
        "You have a photographic memory",
        "You can phase through solid objects",
        "You can summon anyone to immediately come to you",
        "Your pets live exactly as long as you",
        "Everybody who sees you falls in love with you",
        "You can talk to ghosts",
        "You can change your gender at will",
        "You can change your height at will",
        "Everything you say gets an impressive echo behind it",
        "A cool soundtrack follows you your entire life",
        "Unicorns exist",
        "You can always find people with whom to play a game",
        "You can solve any murder crime within a week",
        "Centuries from now, you are named the most influential person ever",
        "You never have to pay for a ticket to anything",
        "Every Sunday, you can spend the day with any historical figure you want",
        "You inherit a chocolate factory from an insane inventor",
        "You always have an impressive six-pack (abs)",
        "You are always motivated for anything",
        "You get the chance to be a kid again for a year",
        "You can save any loved one from dying once",
        "You start your own business and make it the wealthiest in the world",
        "Superpowers exist",
        "You can get a baby instantly by saying a magic word",
        "You never face discrimination or prejudice again",
    ],

    [Pack.EXPERT]: [
        "Your personal boundaries are invisible walls people can't physically cross",
        "Every positive thought somebody has about you is spoken out loud",
        "You can control magnets",
        "You always look beautiful in the mirror (no matter the reality)",
        "Animals are drawn to you and always like you",
        "Your eyes can glow in the dark and change color",
        "You always float a few inches above the ground and require no energy to move",
        "You own a pair of shoes that turn you into an incredible dancer",
        "You can give yourself any skin color you want",
        "You own a weapon that kills any danger to you or your family with 100% success",
        "You always own the latest and best devices / gadgets in any field",
        "You receive a random act of kindness every day",
        "You achieve world peace",
        "You find an answer to world hunger",
        "You can move to a different house for free (whenever you want)",
        "You are never part of any accident",
        "Natural disasters never strike near you",
        "Whenever a valuable of yours breaks, a new one immediately falls from the air",
        "You never do anything embarrassing ever again",
        "You have perfect Wi-Fi wherever you are",
        "Your clothes never need to be washed",
        "You always smell nice",
        "You can take perfect snapshots of a situation by blinking once",
        "You can eat and drink anything without the negative health consequences",
        "You have the power of CTRL+Z (Undo) in real life",
        "You can clean your house with a snap of your fingers",
        "You can hack into anyone's computer or phone",
        "You can play any instrument or use any device by looking at it",
        "All furniture changes shape to perfectly match your body",
        "You suddenly get a thousand times more productive than usual",
        "You are unable to feel fear",
        "You are unable to doubt",
        "You can flip your emotions on and off at will",
        "You win prestigious awards for all you are and ever did",
        "You win every discussion or debate",
        "You're allowed to work/study from home at all times",
        "Virtual reality allows you to live the (digital) life of your dreams",
        "You can turn any task into a fun game without effort",
        "You are in charge of designing all buildings in the world",
        "You find a solution for climate change",
        "Your body can turn food and ideas into electricity",
        "You can go into your past and undo one bad decision",
        "You are always strong, fit and muscular without needing to work for it",
        "You invent an algorithm that gives you the best decision to take every time",
        "You can erase only the bad memories and experiences from your past"
    ],

    [Pack.EXTRAORDINARY]: [
        "You manage to merge all countries in the world into one peaceful unit per continent",
        "You win the award for sexiest body in the world",
        "You are immune to the negative consequences of drugs or alcohol",
        "You can kiss anybody you want and get away with it",
        "You officially become the god of sex",
        "Your intimate parts grow three times as large",
        "You can make one conspiracy theory actually come true",
        "You can steal one thing a day without anyone noticing",
        "You can hypnotize people and make them do what you want",
        "You can convince anyone of your opinion on something",
        "You can move your date of birth by at most 100 years",
        "Your weekend is 4 days long",
        "You can pick one thing to outlaw for everyone in the entire world",
        "You always have more likes or followers than whatever other profile you check out",
        "When you promise something, a magical force ensures you can't break that promise",
        "You can multitask better than anyone in the world",
        "You can say whatever you want without facing backlash",
        "You have infinite bubble wraps to pop at all times",
        "You can look into the sun and touch hot objects without protection",
        "You are the funniest person on earth",
        "You can force any couple to either marry or get divorced",
        "You can change the appearance of other people",
        "You can change one property of a friend or family member per month",
        "You own glasses that can see through clothes and walls",
        "You win every board game or video game you play",
        "You are the best rocket scientist in the world"
    ]
};

// @NOTE: The code automatically adds "... but" before it (and a period after it?)
const NEGATIVE_CARDS:CategoryDataList = 
{
    [Pack.BASE]: [
        "You find everyone ugly and disgusting",
        "Nobody wants to be your friend",
        "Your entire family dies in a car accident",
        "You can only move around by crawling",
        "Your body never reaches adulthood",
        "Your mind never reaches adulthood",
        "You always forget where you are or why",
        "You grow older four times as quickly",
        "You become blind",
        "You become deaf",
        "You become mute",
        "You become disabled",
        "You become a racist",
        "You can't take a single step without twisting your ankle",
        "Sleeping for too long breaks your bones",
        "You trip over something at least once every ten minutes",
        "You have vertigo ( = fear of heights)",
        "You are forever afraid of everything you experienced so far in your life.",
        "Touching another person makes you terminally ill",
        "You become terminally ill",
        "You lose all your memories",
        "You can never make new memories",
        "You are paralyzed",
        "You're deadly allergic to sunshine",
        "You're deadly allergic to rainfall",
        "The weather 100% determines your emotions",
        "You must hibernate in all seasons except one",
        "You get dementia.",
        "You slowly turn into an animal",
        "Your body temperature and hands are always ice cold",
        "Nobody ever remembers an interaction with you",
        "You can't do any calculation besides 1 + 1",
        "You cause a new accident every day",
        "All hooligans in the world are your biggest fans",
        "You get addicted to every piece of media you see",
        "You need to kill one person a year to keep this benefit",
        "You need to stay in school forever to keep this benefit",
        "You may eat only vegetables and nothing else ever again",
        "Everything you eat tastes exactly the same",
        "Your actions cause magic to never be discovered",
        "You can't do anything without making a lot of noise",
        "You must accept every hug somebody offers you",
        "You can only communicate in emojis and neanderthal noises",
        "You can never eat your favorite food again",
        "You must work the job you hate the most to keep this benefit"
    ],

    [Pack.ADVANCED]: [
        "You are always angry or sad when other people come close.",
        "You always correctly guess the plot of movies and books within 5 seconds",
        "Your actions cause the cure for cancer to never be found",
        "Your arms become legs, and your legs become arms",
        "Every night your head is filled with endless nightmares",
        "You're forced to succesfully switch jobs every week, or die",
        "You must do the same routine every single day for the rest of your life",
        "If you hear a lie, you get a panic attack",
        "You are exceptionally unlucky",
        "You are always dizzy",
        "All colors look completely different and random to you",
        "You have the body of an 80-year-old your entire life",
        "Every room smells dirty to you",
        "Whenever you consciously wish for something, it will never become true.",
        "Everything feels searing hot to you",
        "Your body and clothes become transparent",
        "You can never have a pet",
        "You can never have a child",
        "When you die, you reincarnate as a spider",
        "You can't see or hear people of a different gender than you",
        "You can't see or hear people of a different age than you",
        "You are forced to sing and dance 24/7",
        "You must make yourself as ugly as possible to keep this benefit",
        "Ghosts keep talking to you and distracting you",
        "Every touch tickles",
        "You randomly switch languages while talking",
        "You loudly sneeze whenever someone else is talking",
        "You lose money for every minute you sleep",
        "You lose all your degrees and can never finish school again",
        "You are woken up each morning with a bucket of ice cold water splashed over your head",
        "You can only play games when they take 10+ hours to complete",
        "Every year, one person close to you mysteriously disappears",
        "You must work full-time as a telemarketer",
        "It's physically impossible for you to disobey any law",
        "Everything you ever did is forgotten once you die",
        "You're always depressed",
        "You are always tired",
        "You are always sick",
        "It takes years to recover from the smallest of illnesses",
        "You are never motivated for anything",
        "You spend the rest of your life in prison",
        "You can never experience another film, show or book",
        "Everyone is always severely disappointed in you",
        "You are excluded from all social gatherings",
        "All our pets turn into giant beasts that want to eat us",
    ],

    [Pack.EXPERT]: [
        "Everyone constantly crosses your personal boundaries.",
        "You can't help but take over the emotion of whomever is closest to you",
        "Every negative thought somebody has about you arrives in your mail",
        "You have no control over your body, as if you're a puppet for a master",
        "Every time you try to pay for something, your money is suddenly counterfeit",
        "You become a strong magnet, attracting random stuff and repelling the rest",
        "Your mouth emits a burst of confetti every time you laugh",
        "Whenever you hold an object, it always changes shape so it falls out of your hands",
        "Whenever you try to sit down on something, it falls apart",
        "Your hair changes color when you're lying or hiding something",
        "Mirrors talk to you and tell you you're fat and ugly",
        "Whenever you want to say something important, you forget what it was",
        "Whenever you go on a date, you turn invisible",
        "You must do a household chore every hour or you die",
        "All your thoughts float in publicly visible bubbles around your head",
        "You can never wear shoes, gloves or sunglasses again",
        "The better you look, the fewer friends you have",
        "When you die, you take everybody in a 1 mile radius with you",
        "You can never be in the same city as a loved one",
        "Everyone you meet instantly criticizes everything about you",
        "You must live without electricity to keep this benefit",
        "You can never fall in love again",
        "Any time you're accused of something (illegal or not), it becomes true",
        "You are always itchy",
        "You are always in pain",
        "You always have bad breath",
        "You stub your toe every hour",
        "You bite your tongue every time you eat",
        "You always have the hiccups",
        "Your vision is always blurry and your eyes always dry",
        "You can't speak, only sing",
        "You must pause a second after every word spoken",
        "You grow no taller than when you were four years old",
        "You know when and how you die",
        "You lose all pictures you ever took",
        "You must non-stop go to the toilet",
        "You are permanently surrounded by people you dislike",
        "You lose all your limbs",
        "You always wear wet socks and underwear",
        "You can never shower or bathe again",
        "You can never use the internet again",
        "You can only buy, eat or use objects of a single color",
        "No clothes ever fit you",
        "All kids start crying when you come near",
        "You step on a LEGO brick at least once a day",
    ],

    [Pack.EXTRAORDINARY]: [
        "You fart once per minute",
        "No visitors can ever come to your home or events you organize",
        "Rats keep reappearing in your kitchen and eating all the food by morning",
        "Your shadow has its own personality that's the opposite of everything you are",
        "There's always someone walking in front of you at a glacially slow pace",
        "There's always, somehow, a tiny stone inside your shoes",
        "Whenever you pay for something, you feel obliged to yell your code and balance",
        "Whenever somebody exercises near you, you must join them until they're done",
        "You can never have sex",
        "Your legs are as long as fingers, and your fingers as long as your legs",
        "You stumble upon your parents having sex every day",
        "You switch genders every time you burp",
        "Your asshole itches every time you look through a window",
        "Every partner of yours will cheat on you within a week",
        "Your parents watch you every time you have sex",
        "You are drunk all the time",
        "You get immediately addicted to every substance you use",
        "You become autistic",
        "You get a severe hyperactivity disorder",
        "Your clothes teleport to a random location whenever you blink",
        "Whenever you make a mistake, you are tortured",
        "Everything you drink tastes like piss",
        "You are never credited for any of your achievements",
        "The entire online search history of your life becomes public",
        "Everything you ever said or did becomes public knowledge",
        "If you were ever friends with a criminal, you also go to jail",
    ]
}


const NEUTRAL_CARDS:CategoryDataList =
{
    [Pack.BASE]: [
        "While wearing a clown suit and makeup",
        "While living on top of the highest mountain",
        "While having an invisible companion commenting loudly on all you do or think",
        "While aging backward",
        "While you experience everything in slow-motion",
        "While perpetually on stage, even in in private moments",
        "While swapping body with someone else every Sunday",
        "While dancing at all times",
        "While feeling itches in random, unreachable places",
        "While leading a huge company",
        "While dramatically acting out everything you say",
        "While everything happens to you in reverse",
    ],

    [Pack.ADVANCED]: [
        "While speaking and hearing everything through a random accent",
        "While gravity doesn't work on you",
        "While having a bad hair day",
        "While experiencing mood swings",
        "While always misplacing items the first time",
        "While wearing earbuds or headphones at all times",
        "While always being accompanied by a soundtrack or voiceover",
        "While the world is always listening",
        "While laughing at all times",
        "While chewing on gum every second of every day",        
    ],

    [Pack.EXPERT]: [
        "While always speaking through rhymes or hiccups",
        "While either talking deafeningly loud or incomprehensibly soft",
        "While having an infectious sneeze",
        "While never being able to go outside",
        "While never being able to go inside",
        "While everything you do or use somehow makes the wrong noise",
        "While only able to use items with the same general shape",
        "While having the memory of a goldfish",
        "While always offering the wrong handshake during greetings",
        "While raising a large family",
    ],

    [Pack.EXTRAORDINARY]: [
        "While naked",
        "While drunk",
        "While unable to control your bladder",
        "While being unable to have sex without encouragement.",
        "While permanently having sweaty hands and feet",
        "While blushing at all times",
        "While unable to handle emotions without making bad jokes",
        "While stealing a pillow anytime you see one",
        "While unable to recall the names of your best friends or partner",
        "While having a party every single day",
    ]
}

const CARDS:Record<Category, CategoryDataList> = 
{
    [Category.POSITIVE]: POSITIVE_CARDS,
    [Category.NEUTRAL]: NEUTRAL_CARDS,
    [Category.NEGATIVE]: NEGATIVE_CARDS,
}

export 
{
    Pack,
    Category,
    CategoryData,
    TokenType,
    CARDS,
    CATEGORIES,
    TOKEN_TYPES
}
